name: window_toolkit
description: "Toolkit simplifies customization of native user interface components for macOS applications."
version: 0.1.0 
homepage: https://github.com/Codedop/
repository: https://github.com/Codedop/window_toolkit.git
license: MIT 
topics:
  - window
  - window-managment
  - titlebar

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  screen_retriever: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dependency_validator: ^4.1.1
  mockito: ^5.4.4
  test: ^1.25.7

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: WindowToolkitPlugin

platforms:
  macos: